### ISSUE TITLE
Allow metadata in contributions.yaml instead of setup.py

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-benchmarks#2]
When a contribution is a fork on qiskit (or when a `setup.py` is "taken" because some other reason) it would be great to be able to override the metadata by, for example, optional parameters in `contributions.yaml`

```yaml
- git+https://github.com/john-doe/qiskit-terra.git@patch-2:
  passmanagers: 
    - "qiskit.transpiler.level1:level_1_pass_manager"
    - "qiskit.transpiler.level2:level_2_pass_manager"
    - "qiskit.transpiler.level3:level_3_pass_manager"
  metadata: 
    author: John Doe
    author_email: anemail@gmail.com
    description: "More trials are better results"
    name: swap-mapper-trials
```

**Comment by delapuente** [comment]
More format proposals:

## First-item meta:

```yaml
- git+https://github.com/john-doe/qiskit-terra.git@patch-2:
  - author: John Doe
    author_email: anemail@gmail.com
    description: "More trials are better results"
    name: swap-mapper-trials
  - qiskit.transpiler.level1:level_1_pass_manager
  - qiskit.transpiler.level2:level_2_pass_manager
  - qiskit.transpiler.level3:level_3_pass_manager
```

## Object-instead-of-list

```yaml
- git+https://github.com/john-doe/qiskit-terra.git@patch-2:
    author: John Doe
    author_email: anemail@gmail.com
    description: "More trials are better results"
    name: swap-mapper-trials
    entry-points:
      - qiskit.transpiler.level1:level_1_pass_manager
      - qiskit.transpiler.level2:level_2_pass_manager
      - qiskit.transpiler.level3:level_3_pass_manager
```

@karliky @1ucian0 @gines-carrascal thoughts?
